name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nodule dependencies
        run: yarn install --production=true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup module dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install module dependencies
        run:  yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint


      - name: Build
        run: yarn build

      - name: Send build time to airtable;
        uses: ./
        with:
          airtable_base_id: 'appTSR8XIzUujbT9B'
          airtable_table_name: 'tblZ5WBM899aD46b9'
          airtable_token: ${{ secrets.AIRTABLE_TOKEN }}
          build_step_name: 'Setup module dependencies cache'
